Feature/watering plan status update
green-ecolution/green-ecolution-frontend pull request #303
Opened 2024-12-29 17:03 UTC by doriengr

2024-12-31 13:39 UTC, xk0niR requested changes
Since all mentioned Issues/PRs are already merged inside develop, I've only checked out the frontend and using deployed backend.

When opening a watering plan ("Geplant") there is now a new button "Status aktualisieren"
![image](https://github.com/user-attachments/assets/94d673a3-09ca-4fb1-a406-c7bfd18ad57d)

But I am unable to change it's status, "Speichern" is never available (see screenshot)
![image](https://github.com/user-attachments/assets/193a7e3d-8d09-41c3-a496-2c511da02373)


Also for an active watering plan the status-button is not available. It should be to cancel the watering plan or am I missing something?

2025-01-01 11:20 UTC, doriengr commented
> Since all mentioned Issues/PRs are already merged inside develop, I've only checked out the frontend and using deployed backend.
> 
> When opening a watering plan ("Geplant") there is now a new button "Status aktualisieren" ![image](https://private-user-images.githubusercontent.com/41822157/399479419-94d673a3-09ca-4fb1-a406-c7bfd18ad57d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3MzA0NjcsIm5iZiI6MTczNTczMDE2NywicGF0aCI6Ii80MTgyMjE1Ny8zOTk0Nzk0MTktOTRkNjczYTMtMDljYS00ZmIxLWE0MDYtYzdiZmQxOGFkNTdkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAxVDExMTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWExYzc0MjlmODgxYmU5ODUwNzFkODQ3ZDU1NmMxOGI1NDliNGQzNWZhYTc5NDNhNDVmMTMwNzJkOGMzM2VhMmUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.3G0J1OzlvwaTRXnsLd02RJeBRceruAZxiVUFv_gtBcg)
> 
> But I am unable to change it's status, "Speichern" is never available (see screenshot) ![image](https://private-user-images.githubusercontent.com/41822157/399479672-193a7e3d-8d09-41c3-a496-2c511da02373.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU3MzA0NjcsIm5iZiI6MTczNTczMDE2NywicGF0aCI6Ii80MTgyMjE1Ny8zOTk0Nzk2NzItMTkzYTdlM2QtOGQwOS00MWMzLWE0OTYtMmM1MTFkYTAyMzczLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAxVDExMTYwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRiZDRlMWNkYWU2MjJhNjYxNWMyZTE5YTk2ZTI1ZjMwMDQ3M2M5NzlhNjI2YTk2YjRkMGM5MTA2MTEwNWNhOGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.7hyhGHZmiSKhlccrHatTvIQtp-Zh5IklzvldtsaPgIM)
> 

This was my mistake. I used the same form validation roles for creating a new watering plan and updating one. Problem was that I said that the date of a watering plan has to today or in the future. Since you wanted to update a watering plan in the past the validation threw an error. I am using two different validation rules for update and create now and it should hopefully work! 🙏 

> Also for an active watering plan the status-button is not available. It should be to cancel the watering plan or am I missing something?
Also my mistake. I updated it. The watering plan status can be updated if it has a current status of »planned«, »active« or »unknown«

2025-01-03 21:10 UTC, xk0niR requested changes
@doriengr A status update won´t update on first reload (see GIF).
Is this an "easy" fix or should this be another issue?

![status-update-opt](https://github.com/user-attachments/assets/46988434-d220-4aee-8f45-b54bc7597995)

2025-01-03 21:29 UTC, doriengr commented
> @doriengr A status update won´t update on first reload (see GIF). Is this an "easy" fix or should this be another issue?
> 
> ![status-update-opt](https://private-user-images.githubusercontent.com/41822157/400071757-46988434-d220-4aee-8f45-b54bc7597995.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NDAwMTcsIm5iZiI6MTczNTkzOTcxNywicGF0aCI6Ii80MTgyMjE1Ny80MDAwNzE3NTctNDY5ODg0MzQtZDIyMC00YWVlLThmNDUtYjU0YmM3NTk3OTk1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDIxMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGRiYzMzNGU3ODgxNWQ2NTg5Njg1MWZkNDAyN2ZhNDk5Yjk3ZDc4MzMzOWJkNjM5YTAzYzUwMTE4YWE0ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SLxlg6MO9FZTtZGoMVLstSFsZrNjRIsgR1CHzF2cpV8) [ ![status-update-opt](https://private-user-images.githubusercontent.com/41822157/400071757-46988434-d220-4aee-8f45-b54bc7597995.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NDAwMTcsIm5iZiI6MTczNTkzOTcxNywicGF0aCI6Ii80MTgyMjE1Ny80MDAwNzE3NTctNDY5ODg0MzQtZDIyMC00YWVlLThmNDUtYjU0YmM3NTk3OTk1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDIxMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGRiYzMzNGU3ODgxNWQ2NTg5Njg1MWZkNDAyN2ZhNDk5Yjk3ZDc4MzMzOWJkNjM5YTAzYzUwMTE4YWE0ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SLxlg6MO9FZTtZGoMVLstSFsZrNjRIsgR1CHzF2cpV8) ](https://private-user-images.githubusercontent.com/41822157/400071757-46988434-d220-4aee-8f45-b54bc7597995.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NDAwMTcsIm5iZiI6MTczNTkzOTcxNywicGF0aCI6Ii80MTgyMjE1Ny80MDAwNzE3NTctNDY5ODg0MzQtZDIyMC00YWVlLThmNDUtYjU0YmM3NTk3OTk1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDIxMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGRiYzMzNGU3ODgxNWQ2NTg5Njg1MWZkNDAyN2ZhNDk5Yjk3ZDc4MzMzOWJkNjM5YTAzYzUwMTE4YWE0ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SLxlg6MO9FZTtZGoMVLstSFsZrNjRIsgR1CHzF2cpV8) [ ](https://private-user-images.githubusercontent.com/41822157/400071757-46988434-d220-4aee-8f45-b54bc7597995.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzU5NDAwMTcsIm5iZiI6MTczNTkzOTcxNywicGF0aCI6Ii80MTgyMjE1Ny80MDAwNzE3NTctNDY5ODg0MzQtZDIyMC00YWVlLThmNDUtYjU0YmM3NTk3OTk1LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNTAxMDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjUwMTAzVDIxMjgzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTQ3NGRiYzMzNGU3ODgxNWQ2NTg5Njg1MWZkNDAyN2ZhNDk5Yjk3ZDc4MzMzOWJkNjM5YTAzYzUwMTE4YWE0ZjMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.SLxlg6MO9FZTtZGoMVLstSFsZrNjRIsgR1CHzF2cpV8)

This is related to #207 and a bigger problem.

2025-01-03 21:36 UTC, xk0niR approved these changes
Well done, thank you! :+1:

2025-01-04 08:47 UTC, merged